### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by faltfe** [urdh/skdoc#38]
When I try to create a documention using `skdoc` I get the following error.
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! LaTeX error: "kernel/deprecated-command"
! 
! The deprecated command '\ior_get_str:NN' has been or will be removed on
! 2018-03-05. Use instead '\ior_str_get:NN '.
! 
! See the LaTeX3 documentation for further information.
! 
! Type <return> to continue.
!...............................................  
```

The error occurs since I updated my distribution to the latest version.

**Comment by urdh** [comment]
Sorry for the delayed response, for some reason Github decided not to email me about this. I've fixed the issue and will try to get a release up on CTAN soon.
