### ISSUE TITLE
Remove scrpage2 as it is removed and creates an error

### ISSUE THREAD

**Issue by wunderlich** [urdh/skdoc#43]
I just updated my TeXLive distribution and now `scrpage2.sty?`is not found anymore.

The package has been removed: https://www.komascript.de/faq_scrpage2_en.

Most likely you can easily replace

https://github.com/urdh/skdoc/blob/70c7f077d65c9a6a72c884b2ca6c43fc20b8313a/skdoc.dtx#L798

by

```\RequirePackage{scrlayer-scrpage}```.

It is recommended [here](https://tex.stackexchange.com/questions/541766/latex-error-file-scrpage2-sty-not-found) and worked for my document class as well. But know I can't compile my documentation, as it depends on ```skdoc```. :smile:

**Comment by urdh** [comment]
Thanks for the bug report, I'll get a new version published to CTAN soon.
