### ISSUE TITLE
Strange section numbering

### ISSUE THREAD

**Issue by wunderlich** [urdh/skdoc#44]
Hey Simon,

I recognized a strange behaviour, but I'm not able to find its origin. When I compile a LaTeX-document using `skdoc`, the numbering of the sections isn't typeset sans serif and it's indented, as it is in your PDF files:

![grafik](https://user-images.githubusercontent.com/4471366/97123913-506a2480-172e-11eb-942d-9f7cc307e38c.png)

For testing i used your documentation of `skrapport` from GitHub and compiled it under an up to date *TeX Live 2020* (`skdoc` version 1.5c) with `pdfLaTeX`. 

It also happens, if I use a minimal working example:

```
\documentclass{skdoc}

\usepackage{lipsum}

\begin{document}
  \section{Test}
  \subsection{Test}
  
  \lipsum[1]
\end{document}
```

Result:

![grafik](https://user-images.githubusercontent.com/4471366/97124036-cbcbd600-172e-11eb-9b03-a81e265f2ad1.png)

Do you have any idea, where this difference could come from?

Regards and many thanks for your work!

**Comment by urdh** [comment]
Looks like it's an issue with `scrartcl` falling back to a compatibility mode. Will try to get a fix released during the day.

Thanks for the report, sorry I didn't get to it earlier.

**Comment by wunderlich** [comment]
Again, thank you very much!!
